mysite/urls.py
from django.conf.urls import patterns, include, url

# import our settings file to serve static assets
from django.conf import settings


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from polls.api import PollResource

poll_resource = PollResource()
# this is where the main site hands off the users request to different apps should you have them
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    #hands off the request to the polls app
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^api',include(poll_resource.urls)),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),


    # url to match djangos requests for assets (js, css, img) and return them
    # change settings.Dev.... to STATIC_ROOT for production deployment (remember to run collectstatic too)
    # collectstatic pulls static files i.e. js and css and html( files that change often)
    # to the django files (files or infrastructure that will never change or rarely does)
    # so django can put them together to make the awesomeness that is a web page
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

polls/urls.py
# THIS is not the way drew wants the views to be done. He wants functional views
# because too much information is abstracted from the view via generic views
# It is plausible to do that in some instances, however it is not that serious....
#
#
#from django.conf.urls import patterns, url
#
#from polls import views
#
#urlpatterns = patterns('',
#    url(r'^$', views.IndexView.as_view(), name='index'),
#    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
#    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
#    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
#)


# doing views the functional way like below
from django.conf.urls import patterns, url
# from mysite.settings import STATIC_ROOT
from polls import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index, name='index'),

    # ex: /polls/5
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),

    # ex: /polls/5/results/
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),

    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),

   # this url needs too be on the root not here in the apps urls.py
   # url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT})


)

polls/models.py
from django.db import models
import datetime
from django.utils import timezone


# Create your models here. Basically what do you need to represent the data correctly?
# answer that question here of course in models.py don't forget your imports above

# a model representation of Poll table data
class Poll(models.Model):
    # attributes of the model
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    # returns the model in a human readable string in the admin panel and
    # in the template and anywhere else you need it in UTF-8 format
    def __unicode__(self):
        return self.question

    # creates a new table in the database called was_published recently
    # and gives it those attributes in the table and
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


# a model representation of choice table data
class Choice(models.Model):
    poll = models.ForeignKey(Poll, related_name='choices')
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

polls/views.py
# Create your views here.

from django.http import HttpResponse
from django.http import Http404
# from django.template import RequestContext, loader
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse


# import the models to the views page
from polls.models import Choice, Poll


# Drew wants these as functional views because of the awesomeness provided

# What do you need to display these views properly? Ask yourself this question first

# What does the view need to work? It is always the request from the user, and in the
# detail pages the id of what ever item that was clicked on

# What does render need to draw correctly? That would be the parameters in render
# render needs the request first, the template second, and the context instance dictionary,
# which is a dictionary of values to add to the template context, which is usually defined in the
# view itself
def index(request):

    latest_poll_list = Poll.objects.all().order_by('-pub_date')[:5]
    return render(request, 'index.html', {'latest_poll_list': latest_poll_list})


def detail(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'detail.html', {'poll': poll})


def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'results.html', {'poll': poll})


def vote(request, poll_id):

    # needs object to search and the search parameters
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        # if you get the vote post it to the db
        selected_choice = p.choices.get(pk=request.POST['choice'])
   # else post a 404 error
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form
        return render(request, 'detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        }
        )
    else:
        # else go to the next page and show the vote count
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice
        # if a user hist the BACK button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

polls/templates/poll_list.html
{% load url from future %}  {# Deprecated in django 1.6 #}

{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

templates/detail.html
{# remember to run collectstatic in manage.py to update the files any time you make a change to me #}


{# Here is where you would extend the parent template that blocks inherit from #}
{% extends 'index.html' %}
{#<h1>{{ poll.question }}</h1>#}
{#<ul>#}
{#	{% for choice in poll.choice_set.all %}#}
{#	<li>{{ choice.choice_text }}</li>#}
{#	{% endfor %}#}
{#</ul>#}


{# block content is for when you want to overwrite content in an html page #}
{# for django template inheritance. Template inheritance allows you to build a base skeleton template #}
{# that contains all the common elements of your site and defines blocks that child templates can override #}

{% block content %}
{# Here is where if you wanted to still include the attributes from the parent template #}
{# i.e. append them to this page #}
{{ block.super }}

{# then continue with your template logic #}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choices.all %}
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <input type=radio name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
{% endfor %}
<input type="submit" value="Vote" />
</form>

{# don't forget your endblocks #}
{% endblock content %}

{# if you had to create choices via code instead of the admin panel #}
{# remember this here         #}
{# from polls.models import * #}
{# polls= Poll.objects.all    #}
{# poll.choices.all           #}
{# how to create new choice objects #}
{# choice = Choice.objects.create(poll=polls[1], choice_text='I hate the show glee') #}

templates/index.html
{# remember to run collectstatic in manage.py to update the files any time you make a change to me #}

{# load static files i.e., files that are not in python, such as #}
{# the css and js you would need #}
{% load static from staticfiles %}
{% load url from future %}  {# Deprecated in django 1.6 #}

<!doctype html>
<html lang="en">
{% block head %}
<head>
    <meta charset="UTF-8">

    {% block css %}
    {# in the href you put static as shown here to tell django that this is a static file coming #}
    {# from the static folder you provided and the rest is just a regular url #}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    {% endblock css %}

{#    <style type="text/css">#}
{#        a {#}
{#            color: green;#}
{#            font-weight: bold;#}
{#        }#}
{#        a:hover {#}
{#            color: lightblue;#}
{#        }#}
{#    </style>#}
</head>
{% endblock head %}
<body>
    {% block content %}
        <h1>Poll's List</h1>
        {% if latest_poll_list %}
            <ul>
            {% for poll in latest_poll_list %}
                <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    {% endblock content %}
</body>
</html>

templates/polls/results.html
<h1>{{ poll.question }}</h1>

<ul>
    {% for choice in poll.choices.all %}
    <li> {{ choice }} -- votes = {{ choice.votes }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

templates/results.html
{# remember to run collectstatic in manage.py to update the files any time you make a change to me #}


<h1>{{ poll.question }}</h1>

<ul>
    {% for choice in poll.choices.all %}
    <li> {{ choice }} -- votes = {{ choice.votes }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>